### ISSUE TITLE
HPET _CRS to XCRS Rename has a wrong hex number

### ISSUE THREAD

**Issue by catindog** [corpnewt/SSDTTime#33]
The hexadecimal numbers generated by this script are 255f435253 and 2558435253，They are converted to strings of %_ CRS and %XCRS

**Comment by corpnewt** [comment]
This is by design.  If you did a blanket rename of all instances of `_CRS` to `XCRS` - you would be forcing any device that has a defined `_CRS` method to try and utilize IRQs 0, 8, and 11 - which would force IRQ conflicts; thus defeating the entire purpose of the FixHPET approach.  The reason it's padded is to ensure that the hex we're looking for only occurs once in the DSDT - thus only renaming HPET's `_CRS` method, and not every instance within the DSDT.

-CorpNewt
