### ISSUE TITLE
NO Dumping DSDT option found

### ISSUE THREAD

**Issue by vatsal1992** [corpnewt/SSDTTime#35]
Hello there,
First of all ...... _**Thank you sooo much for sharing this script.. I really mean it, man....**_

I'm currently running Hackintosh Catalina 10.15.7 (Clover bootloader).
I want to change my boot loader to OpenCore.
So,I downloaded SSDTTime script (on 28Sep,2020) and when I executed `SSDTTime.command` there was no DSDT dumping option available. so, I tried by running `SSDTTime.py` but the result was same....

So, I don't understand what to do...
Please help me.

I'm attaching both the screenshots for your reference.
![NO DSDT 1](https://user-images.githubusercontent.com/12713108/94450584-11968c80-01cb-11eb-9efc-2794405b8993.png)
![NO DSDT 2](https://user-images.githubusercontent.com/12713108/94450607-152a1380-01cb-11eb-8bca-c203ae556354.png)

**Comment by corpnewt** [comment]
This is by design.  If you're booted into macOS via Clover or OpenCore, any ACPI renames/patches are already applied, so dumping the DSDT from there yields an incorrect representation which won't have proper pathing.  The option will be available if booted into another OS.  You can also dump DSDT via OpenCore and Clover.

-CorpNewt
