### ISSUE TITLE
Missing "Dump DSDT" feature in macOS

### ISSUE THREAD

**Issue by Drovosek01** [corpnewt/SSDTTime#43]
I tried running it .bat file in Windows 10 and there was an item allowing you to get / extract DSDT from the system.

After installing hackintosh, I decided to work with DSDT and used this script. I tried running the. command file and .py file in macOS Mojave 10.14.6, but there was no "Dump DSDT"option in the list of options.
Why?

.py file:
![image](https://user-images.githubusercontent.com/29478700/103708153-14223280-4fc1-11eb-9c38-d327e9973570.png)

.command file:
![image](https://user-images.githubusercontent.com/29478700/103708368-872ba900-4fc1-11eb-8ebc-2e3395b32ff7.png)

**Comment by corpnewt** [comment]
This is by design - if you boot into macOS using Clover or OpenCore, then your DSDT will have been adjusted by those boot managers, making the information SSDTTime would glean potentially inaccurate.  You can use OpenCore/Clover to dump the DSDT directly in the UEFI environment though - which would not have those adjustments.

-CorpNewt
