### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'Scripts'

### ISSUE THREAD

**Issue by zwl1619** [corpnewt/SSDTTime#62]
I ran `SSDTTime.bat` with administrator on windows 11, there is an error:
```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\macos_black\EFI\OC\ACPI\SSDTTime\SSDTTime.py", line 1, in <module>
    from Scripts import downloader, dsdt, plist, reveal, run, utils
ModuleNotFoundError: No module named 'Scripts'

Script exited with error code: 1

Press [enter] to exit...
```

**Comment by corpnewt** [comment]
Hey there - are you sure you've downloaded the entire project?  The [`Scripts`](https://github.com/corpnewt/SSDTTime/tree/master/Scripts) folder is certainly present in this repo - and that's what it's stating it cannot find.

-CorpNewt

**Comment by zwl1619** [comment]
@corpnewt    
Yes, I downloaded the entire project, and there is a discussion:
https://stackoverflow.com/questions/16981921/relative-imports-in-python-3

**Comment by corpnewt** [comment]
That discussion is for relative imports in the same directory - but suggests that the setup being used with SSDTTime currently should work.  Your original error is stating that the `Scripts` folder itself cannot be found:
```
    from Scripts import downloader, dsdt, plist, reveal, run, utils
ModuleNotFoundError: No module named 'Scripts'
```
Rather than a relative import error:
```
ImportError: attempted relative import with no known parent package
```
You did mention that it was run as administrator - does it work as a standard user?  I run Window 10 and simply launching via the SSDTTime.bat starter works fine locally.

-CorpNewt

**Comment by zwl1619** [comment]
I reinstall python with `Windows installer (64-bit)` instead of  `Windows embeddable package (64-bit)`, it is ok now.
